const orb=document.getElementById('orb'),panel=document.getElementById('panel'),state=document.getElementById('state'),chat=document.getElementById('chat'),talk=document.getElementById('talk'),close=document.getElementById('close');
const SR=window.SpeechRecognition||window.webkitSpeechRecognition; let rec=null,history=[];
function setState(s){orb.className=s;state.textContent={ready:'READY • TAP THE CORE TO SPEAK',listening:'LISTENING…',thinking:'THINKING…',speaking:'SPEAKING…',error:'ERROR'}[s]||s}
function add(t,c='j'){const d=document.createElement('div');d.className='m '+c;d.textContent=t;chat.appendChild(d);chat.scrollTop=chat.scrollHeight}
function speak(t){if(!('speechSynthesis'in window)){setState('ready');return}setState('speaking');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.95;u.pitch=.9;u.onend=()=>setState('ready');speechSynthesis.speak(u)}
async function askJarvis(text){add(text,'u');setState('thinking');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');history.push({role:'user',content:text},{role:'assistant',content:data.reply});add(data.reply);speak(data.reply)}catch(e){setState('error');add('JARVIS connection error: '+e.message);setTimeout(()=>setState('ready'),2500)}}
function listen(){if(!rec){add('Voice recognition is unavailable in this browser.');return}navigator.mediaDevices?.getUserMedia({audio:true}).then(()=>{try{rec.start()}catch(e){}}).catch(()=>{setState('error');add('Please allow microphone access.')})}
orb.onclick=()=>{panel.classList.add('open');listen()};close.onclick=()=>panel.classList.remove('open');talk.onclick=listen;
if(SR){rec=new SR();rec.lang='en-US';rec.interimResults=false;rec.continuous=false;rec.onstart=()=>setState('listening');rec.onend=()=>{if(orb.className==='listening')setState('ready')};rec.onerror=e=>{setState('error');add('Microphone error: '+e.error);setTimeout(()=>setState('ready'),2000)};rec.onresult=e=>askJarvis(e.results[0][0].transcript.trim())}setState('ready');
