const orb=document.getElementById('orb'),panel=document.getElementById('panel'),state=document.getElementById('state'),chat=document.getElementById('chat'),talk=document.getElementById('talk'),close=document.getElementById('close');
let rec=null,stream=null,chunks=[],busy=false,history=[];
function status(x){state.textContent=x}
function add(t,c='j'){const d=document.createElement('div');d.className='m '+c;d.textContent=t;chat.appendChild(d);chat.scrollTop=chat.scrollHeight}
function say(t){if(!window.speechSynthesis){status('READY');return}status('SPEAKING…');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.onend=()=>status('READY • TAP TALK TO SPEAK');speechSynthesis.speak(u)}
async function sendText(text){status('THINKING…');add(text,'u');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI request failed');history.push({role:'user',content:text},{role:'assistant',content:d.reply});add(d.reply);say(d.reply)}catch(e){add('JARVIS error: '+e.message);status('READY • TAP TALK TO SPEAK')}}
async function start(){if(busy)return;busy=true;try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];rec=new MediaRecorder(stream);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());talk.textContent='🎙️ Talk';status('THINKING…');try{const f=new FormData();f.append('audio',new Blob(chunks,{type:rec.mimeType}),'voice.webm');const r=await fetch('/api/voice',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw new Error(d.error||'Voice upload failed');await sendText(d.text)}catch(e){add('Voice error: '+e.message);status('READY • TAP TALK TO SPEAK')}busy=false};rec.start();talk.textContent='⏹️ Stop';status('LISTENING…')}catch(e){add('Microphone permission was not granted.');status('READY • TAP TALK TO SPEAK');busy=false}}
function stop(){if(rec&&rec.state==='recording')rec.stop()}
orb.onclick=()=>panel.classList.add('open');close.onclick=()=>panel.classList.remove('open');talk.onclick=()=>rec&&rec.state==='recording'?stop():start();
